workflows:
  unity-android:
    name: Build Unity for Android
    environment:
      unity: latest
      vars:
        UNITY_PROJECT_PATH: "SnakeGame"
    scripts:
      - name: فك الضغط
        script: unzip SnakeGame.zip -d $UNITY_PROJECT_PATH
      - name: بناء APK
        script: |
          unity-editor             -quit -batchmode -nographics             -projectPath $UNITY_PROJECT_PATH             -executeMethod BuildScript.BuildAndroid             -logFile /dev/stdout
    artifacts:
      - build/**/*.apk
