workflows:
  unity-workflow:
    name: Unity Build
    instance_type: linux
    max_build_duration: 60
    environment:
      vars:
        UNITY_VERSION: 6000.0.0f1
    scripts:
      - name: Unzip project
        script: |
          unzip MyUnityGame.zip -d .
      - name: Unity Build
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode -nographics -quit \
            -projectPath . \
            -buildTarget Android \
            -customBuildName mygame \
            -customBuildPath build/mygame.apk \
            -executeMethod BuildScript.Build
    artifacts:
      - build/mygame.apk
