workflows:
  build-android:
    name: Snake.Balest Build (Free)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        UNITY_VERSION_PRIMARY: 2021.3.20f1
        UNITY_VERSION_FALLBACK: 2020.3.48f1
        PROJECT_ZIP: Snake.Balest.zip
        PROJECT_DIR: Snake.Balest
    scripts:
      - name: Unzip project
        script: |
          echo "Unzipping $PROJECT_ZIP..."
          unzip -o "$PROJECT_ZIP" -d .
      - name: Detect Unity
        script: |
          if [ -d "/Applications/Unity/Hub/Editor/$UNITY_VERSION_PRIMARY" ]; then
            echo "Using primary $UNITY_VERSION_PRIMARY"
            UNITY_VERSION=$UNITY_VERSION_PRIMARY
          else
            echo "Primary not found, using fallback $UNITY_VERSION_FALLBACK"
            UNITY_VERSION=$UNITY_VERSION_FALLBACK
          fi
      - name: Build APK
        script: |
          cd "$PROJECT_DIR"
          UNITY_PATH="/Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity"
          if [ -x "$UNITY_PATH" ]; then
            "$UNITY_PATH" -batchmode -nographics -quit -projectPath . -executeMethod BuildScript.BuildAndroid -logFile /dev/stdout || (echo "APK build failed" >&2; exit 1)
          elif command -v unity-editor >/dev/null 2>&1; then
            unity-editor -batchmode -nographics -quit -projectPath . -executeMethod BuildScript.BuildAndroid -logFile /dev/stdout || (echo "APK build failed" >&2; exit 1)
          else
            echo "Unity not found" >&2; exit 2
          fi
    artifacts:
      - $PROJECT_DIR/build/*.apk
