workflows:
  unity-workflow:
    name: Unity Build
    max_build_duration: 30
    environment:
      vars:
        UNITY_HOME: /Applications/Unity/Hub/Editor/2022.3.0f1
    scripts:
      - name: Unzip project
        script: |
          unzip SnakeGame.zip -d .
      - name: Build Unity project
        script: |
          /Applications/Unity/Hub/Editor/2022.3.0f1/Unity           -quit -batchmode -nographics           -projectPath SnakeGame           -executeMethod BuildScript.BuildAndroid
    artifacts:
      - build/**/*.apk
