workflows:
  unity-android:
    name: Unity Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        UNITY_VERSION: 2021.3.25f1
    scripts:
      - name: Unzip project
        script: |
          unzip Snake3D_Advanced.zip -d .
      - name: Build Android
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity -batchmode -nographics -quit -projectPath Snake3D_Advanced -buildTarget Android -executeMethod BuildScript.BuildAndroid
    artifacts:
      - build/android/*.apk
