workflows:
  android-unity:
    name: Build Unity Android
    max_build_duration: 30
    instance_type: mac_mini_m1

    environment:
      groups:
        - unity_credentials   # لو عندك حساب Unity Hub
      vars:
        UNITY_VERSION: "2022.3.0f1"

    scripts:
      - name: Build Android APK
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity             -batchmode             -nographics             -quit             -projectPath .             -buildTarget Android             -customBuildPath build/mygame.apk

    artifacts:
      - build/mygame.apk
